image:
  repository: ghcr.io/baruchihalamish20/order-service
  tag: "475514b"
env:
  - name: SECRET_KEY
    value: "dev-secret-order"
  - name: APP_ENV
    value: "dev"

service:
  type: NodePort
  port: 80
  nodePort: 30012